name: Deploy to GCP VM via Docker

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy via Docker
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and run tests
        run: |
          python3.12 -m pip install --upgrade pip
          python3.12 -m pip install -r requirements.txt
          python3.12 -m pytest

      - name: Build Docker image
        run: docker build -t mlops-health-risk-api .

      - name: Restart Docker container
        run: |
          docker stop mlops-health-risk-api || true
          docker rm mlops-health-risk-api || true
          docker run -d -p 5000:5000 --name mlops-health-risk-api mlops-health-risk-api
